package com.makewheels.dashcam;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.Color;
import android.graphics.Typeface;
import android.net.*;
import android.os.*;
import android.provider.*;
import android.view.*;
import android.widget.*;
import androidx.documentfile.provider.DocumentFile;
import org.json.*;
import java.io.*;
import java.net.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.*;

public final class MainActivity extends Activity {
    Store store;SharedPreferences prefs;LinearLayout list;TextView source,status,summary,overall;ProgressBar progress,overallProgress;
    final ExecutorService executor=Executors.newSingleThreadExecutor();final Handler handler=new Handler(Looper.getMainLooper());
    boolean cloud=false,resumed=false;JSONArray cloudItems=new JSONArray();String next=null;boolean loading=false;
    int lastCount=-1;String lastRows="";final Map<String,TextView> rowProgress=new HashMap<>();
    @Override public void onCreate(Bundle state){super.onCreate(state);store=new Store(this);prefs=getSharedPreferences("settings",0);build();UploadWorker.schedule(this);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=android.content.pm.PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},8);if(System.currentTimeMillis()-prefs.getLong("update_checked",0)>24*60*60*1000L)checkUpdates(true);}
    int dp(int n){return (int)(n*getResources().getDisplayMetrics().density);}
    TextView text(String value,int size,int color){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,dp(5),0,dp(5));return t;}
    Button button(String name,Runnable run){Button b=new Button(this);b.setText(name);b.setAllCaps(false);b.setOnClickListener(v->run.run());return b;}
    void build(){
        LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(20),dp(12),dp(20),dp(10));page.setBackgroundColor(Color.rgb(245,247,246));setContentView(page);
        LinearLayout title=new LinearLayout(this);TextView heading=text("行车转存",27,Color.rgb(25,52,46));heading.setTypeface(null,Typeface.BOLD);title.addView(heading,new LinearLayout.LayoutParams(0,-2,1));title.addView(button("设置",this::settings));page.addView(title);
        page.addView(text("复制到手机 · 校验后上传",13,Color.GRAY));
        overall=text("",13,Color.DKGRAY);page.addView(overall);overallProgress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);overallProgress.setMax(1000);page.addView(overallProgress);
        source=text("",13,Color.DKGRAY);page.addView(source);source.setOnClickListener(v->choose());
        LinearLayout actions=new LinearLayout(this);actions.addView(button("选文件夹",this::choose),new LinearLayout.LayoutParams(0,-2,1));actions.addView(button("复制 / 继续",this::scan),new LinearLayout.LayoutParams(0,-2,1));page.addView(actions);
        status=text("准备就绪",16,Color.rgb(22,125,110));page.addView(status);
        progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(1000);page.addView(progress);
        summary=text("",12,Color.GRAY);page.addView(summary);
        LinearLayout controls=new LinearLayout(this);controls.addView(button("上传 / 继续",this::upload),new LinearLayout.LayoutParams(0,-2,1));controls.addView(button("暂停",()->TransferEngine.stop(this)),new LinearLayout.LayoutParams(0,-2,1));page.addView(controls);
        LinearLayout tabs=new LinearLayout(this);tabs.addView(button("未上传",()->{cloud=false;refresh();}),new LinearLayout.LayoutParams(0,-2,1));tabs.addView(button("已上传",()->{cloud=true;loadCloud(false);}),new LinearLayout.LayoutParams(0,-2,1));page.addView(tabs);
        ScrollView scroll=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);scroll.addView(list);page.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));refresh();
    }
    @Override protected void onResume(){super.onResume();resumed=true;handler.post(tick);refresh();if(!prefs.getBoolean("upload_paused",false)&&new TransferEngine(this).wifi()&&!TransferEngine.BUSY.get())UploadWorker.schedule(this);}
    @Override protected void onPause(){resumed=false;handler.removeCallbacks(tick);super.onPause();}
    @Override protected void onDestroy(){executor.shutdownNow();super.onDestroy();}
    final Runnable tick=new Runnable(){public void run(){if(!resumed)return;status.setText(TransferEngine.message);summary.setText(TransferEngine.detail());progress.setProgress(TransferEngine.total>0?(int)(TransferEngine.done*1000/TransferEngine.total):0);updateOverall();List<Store.Item> items=store.files("state!='uploaded'");StringBuilder signature=new StringBuilder();for(Store.Item f:items)signature.append(f.id).append(f.state).append(f.error);if(!signature.toString().equals(lastRows)){lastRows=signature.toString();if(!cloud)renderLocal();}for(var entry:rowProgress.entrySet()){boolean active=entry.getKey().equals(TransferEngine.activeId)&&TransferEngine.BUSY.get();entry.getValue().setVisibility(active?View.VISIBLE:View.GONE);if(active)entry.getValue().setText(TransferEngine.detail());}handler.postDelayed(this,1000);}};
    void updateOverall(){List<Store.Item> active=store.files("id=?",TransferEngine.activeId);if(active.isEmpty()){overall.setText("可用空间 "+TransferEngine.bytes(TransferEngine.free(this))+" · 预留 5 GB");overallProgress.setProgress(0);return;}Store.Item current=active.get(0);List<Store.Item> batch=store.files("batch=?",current.batch);boolean upload=TransferEngine.message.startsWith("上传")||TransferEngine.message.startsWith("云端")||TransferEngine.message.startsWith("清理")||current.state.equals("uploaded");long size=0,done=0;int completed=0;for(Store.Item item:batch){size+=item.size;boolean finished=upload?(item.state.equals("uploaded")||item.state.equals("cleanup_error")):item.sha!=null;if(finished){done+=item.size;completed++;}else if(item.id.equals(current.id))done+=Math.min(item.size,upload?(TransferEngine.message.startsWith("上传 · ")?TransferEngine.done:0):Math.max(item.offset,TransferEngine.done));}overall.setText((upload?"上传":"复制")+"总进度 · "+completed+"/"+batch.size()+" 个 · "+TransferEngine.bytes(done)+" / "+TransferEngine.bytes(size));overallProgress.setProgress(size>0?(int)(done*1000/size):0);}
    void choose(){if(TransferEngine.BUSY.get()){toast("请先暂停当前传输");return;}Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION|Intent.FLAG_GRANT_PREFIX_URI_PERMISSION);String old=prefs.getString("source_tree",null);if(old!=null)i.putExtra(DocumentsContract.EXTRA_INITIAL_URI,Uri.parse(old));startActivityForResult(i,7);}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==7&&result==RESULT_OK&&data!=null&&data.getData()!=null){Uri tree=data.getData();try{int rw=Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION;if((data.getFlags()&rw)!=rw)throw new SecurityException("目录未授予读写权限");getContentResolver().takePersistableUriPermission(tree,Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);prefs.edit().putString("source_tree",tree.toString()).apply();refresh();}catch(Exception e){toast("目录授权失败，请重新选择可读写的视频目录");}}if(request==9&&getPackageManager().canRequestPackageInstalls())install();}
    void refresh(){String tree=prefs.getString("source_tree",null);String name="未选择 · 点击选择读卡器的视频目录";if(tree!=null){DocumentFile d=DocumentFile.fromTreeUri(this,Uri.parse(tree));name="来源："+(d==null?"需要重新授权":d.getName())+" · 手机剩余 "+TransferEngine.bytes(TransferEngine.free(this));}source.setText(name);if(cloud)renderCloud();else renderLocal();}
    void scan(){
        if(TransferEngine.BUSY.get()){toast("当前任务正在运行，请先暂停");return;}String tree=prefs.getString("source_tree",null);if(tree==null){choose();return;}
        status.setText("扫描视频与检查空间…");executor.execute(()->{try{
            String pending=null;try(Cursor c=store.getReadableDatabase().rawQuery("SELECT id FROM batches WHERE tree=? AND ready=0 ORDER BY rowid DESC LIMIT 1",new String[]{tree})){if(c.moveToFirst())pending=c.getString(0);}
            if(pending!=null){String batch=pending;runOnUiThread(()->start(batch,false));return;}
            // A finished import can still have source deletion work after an interruption.
            try(Cursor c=store.getReadableDatabase().rawQuery("SELECT b.id FROM batches b WHERE b.tree=? AND b.ready=1 AND b.delete_source=1 AND EXISTS(SELECT 1 FROM files f WHERE f.batch=b.id AND f.source_deleted=0) ORDER BY b.rowid LIMIT 1",new String[]{tree})){if(c.moveToFirst()){String batch=c.getString(0);runOnUiThread(()->start(batch,false));return;}}
            DocumentFile dir=DocumentFile.fromTreeUri(this,Uri.parse(tree));if(dir==null||!dir.exists()||!dir.canRead())throw new IOException("读卡器未连接或目录授权失效，请重插或重新选择");
            ArrayList<DocumentFile> files=new ArrayList<>();long size=0;for(DocumentFile f:dir.listFiles())if(f.isFile()){if(f.length()<=0)throw new IOException("存在无法读取或空文件："+f.getName());files.add(f);size+=f.length();}
            if(files.isEmpty())throw new IOException("目录内没有文件");if(TransferEngine.free(this)<size+TransferEngine.RESERVE)throw new IOException("空间不足，请清理至少 "+TransferEngine.bytes(size+TransferEngine.RESERVE-TransferEngine.free(this))+"，保留 5 GB 后再复制");
            files.sort(Comparator.comparing(f->f.getName()==null?"":f.getName()));String batch=UUID.randomUUID().toString();String date=new SimpleDateFormat("yyyy-MM-dd",Locale.CHINA).format(new Date());
            var db=store.getWritableDatabase();db.beginTransaction();try{ContentValues bv=new ContentValues();bv.put("id",batch);bv.put("tree",tree);bv.put("delete_source",prefs.getBoolean("delete_source",true)?1:0);db.insertOrThrow("batches",null,bv);
                for(DocumentFile file:files){ContentValues v=new ContentValues();v.put("id",UUID.randomUUID().toString());v.put("batch",batch);v.put("source",file.getUri().toString());v.put("tree",tree);v.put("name",file.getName());v.put("size",file.length());v.put("modified",file.lastModified());v.put("date",date);db.insertOrThrow("files",null,v);}db.setTransactionSuccessful();}finally{db.endTransaction();}
            runOnUiThread(()->{cloud=false;refresh();start(batch,false);});
        }catch(Exception e){runOnUiThread(()->{TransferEngine.message=TransferEngine.readable(e);status.setText(TransferEngine.message);toast(TransferEngine.message);});}});
    }
    void start(String batch,boolean cellular){prefs.edit().putBoolean("upload_paused",false).apply();Intent i=new Intent(this,TransferService.class);if(batch!=null)i.putExtra("batch",batch);i.putExtra("cellular",cellular);startForegroundService(i);}
    void upload(){if(TransferEngine.BUSY.get()){toast("任务正在运行");return;}TransferEngine engine=new TransferEngine(this);if(!engine.connected()){toast("请先连接网络");return;}if(!engine.wifi())new AlertDialog.Builder(this).setTitle("使用移动网络上传").setMessage("视频可能占用较多流量。本次允许上传；中断后需再次手动启动。").setNegativeButton("取消",null).setPositiveButton("开始上传",(d,w)->start(null,true)).show();else start(null,false);}
    void renderLocal(){if(cloud)return;list.removeAllViews();rowProgress.clear();List<Store.Item> files=store.files("state!='uploaded'");long size=0;for(Store.Item f:files)size+=f.size;list.addView(text(files.size()+" 个未上传 · "+TransferEngine.bytes(size),14,Color.DKGRAY));if(files.isEmpty())list.addView(text("插入读卡器，选择视频文件夹后点复制。\nWi-Fi 自动上传，也可以手动开始。",16,Color.GRAY));
        for(Store.Item f:files){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(12),dp(7),dp(12),dp(7));row.setBackgroundColor(Color.WHITE);TextView name=text(f.name,15,Color.DKGRAY);row.addView(name);String state=switch(f.state){case "waiting"->"等待复制";case "copying"->"复制中";case "verifying"->"校验中";case "ready"->"等待上传";case "uploading"->"上传中";case "cleanup_error"->"已上传，待清理手机副本";default->"已暂停或失败，可继续";};row.addView(text(f.date+" · "+TransferEngine.bytes(f.size)+" · "+state,12,Color.GRAY));TextView perFile=text("",12,Color.rgb(22,125,110));perFile.setVisibility(View.GONE);rowProgress.put(f.id,perFile);row.addView(perFile);if(f.error!=null&&!f.error.isEmpty())row.addView(text(f.error,12,Color.rgb(165,70,40)));row.setOnClickListener(v->{if(f.dest!=null)play(Uri.parse(f.dest),"video/*");});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(8);list.addView(row,p);}
    }
    void loadCloud(boolean more){if(loading)return;loading=true;list.removeAllViews();list.addView(text("读取云端列表…",15,Color.GRAY));executor.execute(()->{try{JSONObject result=Api.call("GET","/videos"+(more&&next!=null?"?before="+URLEncoder.encode(next,"UTF-8"):""),null);JSONArray fetched=result.getJSONArray("videos");if(!more)cloudItems=new JSONArray();for(int i=0;i<fetched.length();i++)cloudItems.put(fetched.getJSONObject(i));next=result.isNull("next")?null:result.optString("next",null);runOnUiThread(this::renderCloud);}catch(Exception e){runOnUiThread(()->{list.removeAllViews();list.addView(text("读取失败："+TransferEngine.readable(e),14,Color.GRAY));list.addView(button("重试",()->loadCloud(false)));});}finally{loading=false;}});}
    void renderCloud(){if(!cloud)return;list.removeAllViews();list.addView(button("刷新云端列表",()->loadCloud(false)));if(cloudItems.length()==0)list.addView(text("还没有已上传的视频",16,Color.GRAY));for(int i=0;i<cloudItems.length();i++){JSONObject video=cloudItems.optJSONObject(i);String label=video.optString("name")+"\n"+video.optString("date")+" · "+TransferEngine.bytes(video.optLong("size"))+("missing".equals(video.optString("state"))?" · 云端文件已不存在":"");list.addView(button(label,()->executor.execute(()->{try{JSONObject result=Api.call("GET","/videos/"+video.getString("_id")+"/url",null);runOnUiThread(()->play(Uri.parse(result.optString("url")),"video/*"));}catch(Exception e){runOnUiThread(()->toast(TransferEngine.readable(e)));}})));}if(next!=null)list.addView(button("加载更多",()->loadCloud(true)));}
    void play(Uri uri,String mime){try{startActivity(new Intent(Intent.ACTION_VIEW).setDataAndType(uri,mime).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION));}catch(ActivityNotFoundException e){toast("没有可用播放器；不影响复制和上传");}}
    void settings(){LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(20),dp(8),dp(20),dp(8));CheckBox delete=new CheckBox(this);delete.setText("整批校验通过后自动删除 TF 卡原视频");delete.setChecked(prefs.getBoolean("delete_source",true));delete.setOnCheckedChangeListener((b,on)->prefs.edit().putBoolean("delete_source",on).apply());content.addView(delete);content.addView(button("更换来源文件夹",this::choose));content.addView(button("检查更新 · "+BuildConfig.VERSION_NAME,this::updates));content.addView(button("后台运行设置",()->{try{startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())));}catch(Exception e){toast("请在系统设置中允许后台运行");}}));new AlertDialog.Builder(this).setTitle("设置").setView(content).setPositiveButton("完成",null).show();}
    void updates(){checkUpdates(false);}
    void checkUpdates(boolean quiet){if(!quiet)toast("正在检查更新");executor.execute(()->{try{JSONObject version=Api.call("GET","/updates/android",null);prefs.edit().putLong("update_checked",System.currentTimeMillis()).apply();if(version.optInt("version_code")<=BuildConfig.VERSION_CODE){if(!quiet)runOnUiThread(()->toast("当前已是最新版本"));return;}runOnUiThread(()->{if(isFinishing()||isDestroyed())return;new AlertDialog.Builder(this).setTitle("发现新版本 "+version.optString("version_name")).setMessage(version.optString("notes","改进传输体验")).setNegativeButton("稍后",null).setPositiveButton("下载并安装",(d,w)->download(version)).show();});}catch(Exception e){if(!quiet)runOnUiThread(()->toast(TransferEngine.readable(e)));}});}
    void download(JSONObject version){executor.execute(()->{File apk=new File(getCacheDir(),"update.apk");try{HttpURLConnection c=(HttpURLConnection)new URL(version.getString("url")).openConnection();c.setConnectTimeout(20000);c.setReadTimeout(60000);try{if(c.getResponseCode()!=200)throw new IOException("下载链接失效，请重新检查更新");long length=version.getLong("size");if(TransferEngine.free(this)<length+TransferEngine.RESERVE)throw new IOException("请清理手机空间后更新");try(InputStream in=c.getInputStream();OutputStream out=new FileOutputStream(apk)){byte[] b=new byte[128*1024];int n;long received=0;while((n=in.read(b))!=-1){out.write(b,0,n);received+=n;if(received>length)throw new IOException("安装包大小不匹配");}if(received!=length)throw new IOException("安装包未下载完整");}}finally{c.disconnect();}String[] digest;try(InputStream in=new FileInputStream(apk)){digest=Digests.hash(in,n->{});}if(!digest[0].equals(version.getString("sha256")))throw new IOException("安装包校验失败");runOnUiThread(this::install);}catch(Exception e){apk.delete();runOnUiThread(()->toast(TransferEngine.readable(e)));}});}
    void install(){if(!getPackageManager().canRequestPackageInstalls()){new AlertDialog.Builder(this).setMessage("需要允许本应用安装更新，设置完成后返回即可继续。").setPositiveButton("打开设置",(d,w)->startActivityForResult(new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:"+getPackageName())),9)).setNegativeButton("取消",null).show();return;}try{startActivity(new Intent(Intent.ACTION_VIEW).setDataAndType(Uri.parse("content://"+getPackageName()+".install/update.apk"),"application/vnd.android.package-archive").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION));}catch(Exception e){toast("无法打开安装器");}}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
